CREATE TABLE roles (

id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
nome VARCHAR(50) UNIQUE NOT NULL

);

CREATE TABLE usuarios (

id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
senha VARCHAR(255) NOT NULL,
ativo BOOLEAN DEFAULT TRUE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE usuario_roles (

usuario_id UUID NOT NULL,
role_id UUID NOT NULL,
PRIMARY KEY (usuario_id, role_id),
FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE calendarios (

id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
descricao TEXT,
cor VARCHAR(7) NOT NULL,
usuario_id UUID NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE TABLE eventos (

id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
titulo VARCHAR(200) NOT NULL,
descricao TEXT,
data_inicio TIMESTAMP NOT NULL,
data_fim TIMESTAMP NOT NULL,
local VARCHAR(200),
cor VARCHAR(7),
dia_inteiro BOOLEAN DEFAULT FALSE NOT NULL,
recorrente BOOLEAN DEFAULT FALSE NOT NULL,
tipo_recorrencia VARCHAR(20),
calendario_id UUID NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
FOREIGN KEY (calendario_id) REFERENCES calendarios (id) ON DELETE CASCADE
);

CREATE TABLE compartilhamentos (
id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
calendario_id UUID NOT NULL,
usuario_id UUID NOT NULL,
permissao VARCHAR(20) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
FOREIGN KEY (calendario_id) REFERENCES calendarios (id) ON DELETE CASCADE,
FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
UNIQUE (calendario_id, usuario_id)
);